In [1]:
import numpy as np
prices = np.array([5.99,6.99,22.49,99.99,4.99,49.99])
prices

array([ 5.99,  6.99, 22.49, 99.99,  4.99, 49.99])

In [3]:
prices.sort()
prices

array([ 4.99,  5.99,  6.99, 22.49, 49.99, 99.99])

In [9]:
top_three=prices[-1:-4:-1] # prices[-3:] will also give same results
top_three

array([99.99, 49.99, 22.49])

In [18]:
mean = top_three.mean() 
minimum = top_three.min()
maximum = top_three.max()
Median=np.median(top_three)

# mean , median, min and max
print(mean)
print(minimum)
print(maximum)
print(Median)

57.49
22.49
99.99
49.99


In [20]:
price_tier=np.array(['budget','budget','mid-tier','luxury','mid-tier','luxury'])
price_tier

array(['budget', 'budget', 'mid-tier', 'luxury', 'mid-tier', 'luxury'],
      dtype='<U8')

In [22]:
unique_tier_array=np.unique(price_tier) # for having unique tier elements
unique_tier_array

array(['budget', 'luxury', 'mid-tier'], dtype='<U8')

In [30]:
unique_tier_array.size  # size of array having unique price tier

3