In [1]:
import numpy as np
rng=np.random.default_rng(2022)
array1=rng.random(9).reshape(3,3)
array1  # it will give 9 random numbers in 3d form. seed is same as previous assignment i.e. 2022

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

In [3]:
array1[:2,:] #first two rows

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778]])

In [7]:
array1[:,:1].T #only first column is required that is in form form of row i.e. transposed

array([[0.24742606, 0.06066207, 0.1108689 ]])