In [6]:
import numpy as np
array1 = np.linspace(10,100,10)
array1

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [7]:
array1.reshape(5,2)

array([[ 10.,  20.],
       [ 30.,  40.],
       [ 50.,  60.],
       [ 70.,  80.],
       [ 90., 100.]])

In [10]:
rng = np.random.default_rng(2022)
random_array= rng.random(9)
random_array

array([0.24742606, 0.09299006, 0.61176337, 0.06066207, 0.66103343,
       0.75515778, 0.1108689 , 0.04305584, 0.41441747])

In [11]:
random_array.reshape(3,3)

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])