In [2]:
import numpy as np
prices = np.array([5.99,6.99,22.49,99.99,4.99,49.99])
total_prices= prices+5
total_prices

array([ 10.99,  11.99,  27.49, 104.99,   9.99,  54.99])

In [4]:
rng=np.random.default_rng(2022)
random_array=rng.random(9).reshape(3,3)
random_array

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

In [9]:
random_array2 = random_array[0:2:,:] #first six elements are taken as per requirement
random_array2

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778]])

In [15]:
discount_pct = random_array2.reshape(1,6) #extracted 6 random elements are arranged in one row as per requirement and named discount_pct
discount_pct # discount_pct = random_array2.reshape(6) this will also give same result

array([[0.24742606, 0.09299006, 0.61176337, 0.06066207, 0.66103343,
        0.75515778]])

In [13]:
pct_owed=1-discount_pct #subtrcat discount_pct from 1 and store in the pct_owed as per requirement
pct_owed

array([[0.75257394, 0.90700994, 0.38823663, 0.93933793, 0.33896657,
        0.24484222]])

In [14]:
final_amount=total_prices*pct_owed
final_amount

array([[ 8.27078756, 10.87504916, 10.67262487, 98.6210889 ,  3.38627605,
        13.4638738 ]])

In [17]:
final_amount.round(2)  # this will round of the values upto 2 decimals

array([[ 8.27, 10.88, 10.67, 98.62,  3.39, 13.46]])

In [30]:
print("Total Prices of items",total_prices)
print("Discount'",discount_pct)
print("Discount given",pct_owed)
print("Final Amount after discounts",final_amount.astype('int'))

Total Prices of items [ 10.99  11.99  27.49 104.99   9.99  54.99]
Discount' [[0.24742606 0.09299006 0.61176337 0.06066207 0.66103343 0.75515778]]
Discount given [[0.75257394 0.90700994 0.38823663 0.93933793 0.33896657 0.24484222]]
Final Amount after discounts [[ 8 10 10 98  3 13]]
