In [1]:
print("Allah pak")

Allah pak


In [3]:
a=1
b=2
sum=a+b
print("sum",sum)

sum 3


In [3]:
import numpy as np
list1= ([0,1,2,3,4,5])
array1 = np.array(list1).reshape(2,3)
array1

array([[0, 1, 2],
       [3, 4, 5]])

In [33]:
array1.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [15]:
array2 =np.linspace(0,100,11)
array2= array2.astype('int')
array2

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [19]:
list3=(['a','e','i','o','u'])
array3 = np.array(list3)
array4 = np.array(([1,2,3,4,5]))
print(array3)
print(array4)

['a' 'e' 'i' 'o' 'u']
[1 2 3 4 5]


In [20]:
array3[array4==1]

array(['a'], dtype='<U1')